spring:
  application:
    name: edge-server
  lifecycle:
    timeout-per-shutdown-phase: 15s
  data:
    redis:
      host: localhost
      port: 6379
      connect-timeout: 2s
      timeout: 1s
  session:
#    store-type: redis
    timeout: 10m
    redis:
      namespace: travelbookingsystem:edgeserver
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${spring.application.name}
            client-secret: Q9Py2cdbDzwhXGeM9qXvSQShP47WUgRt
            scope: openid
        provider:
          keycloak:
            issuer-uri: http://localhost:4455/realms/travel-booking-system
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - name: SaveSession
            - name: Retry
              args:
                retries: 3
                methods: GET
                series: SERVER_ERROR
                exceptions: java.io.IOException, java.util.concurrent.TimeoutException
                backoff:
                  firstBackoff: 50ms
                  maxBackoff: 500ms
                  factor: 2
                  basedOnPreviousValue: false
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenish-rate: 10
                  burstCapacity: 20
                  requestedTokens: 1
          httpclient:
            connect-timeout: 2000
            response-timeout: 5s
            pool:
              type: elastic
              max-idle-time: 15s
              max-life-time: 60s
          routes:
            - id: flight-service-route
              uri: ${FLIGHT_SERVICE_URI:http://localhost:8899}
              predicates:
                - Path=/flight-service/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1
                - name: CircuitBreaker
                  args:
                    name: flightServiceCircuitBreaker
                    fallbackUri: forward:/flight-service-fallback
            - id: flight-booking-service-route
              uri: ${FLIGHT_BOOKING_SERVICE_URI:http://localhost:7788}
              predicates:
                - Path=/flight-booking-service/**
              filters:
                - name: StripPrefix
                  args:
                    parts: 1
                - name: CircuitBreaker
                  args:
                    name: flightBookingServiceCircuitBreaker

server:
  netty:
    idle-timeout: 15s
    connection-timeout: 2s
  shutdown: graceful
  port: 6677

logging:
  level:
    io.github.resilience4j: DEBUG

resilience4j:
  circuitbreaker:
    configs:
      default:
        sliding-window-size: 20
        permitted-number-of-calls-in-half-open-state: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 15000
  timelimiter:
    configs:
      default:
        timeout-duration: 5s